package exception

import "errors"

var EX_KEYSTONE_AUTH_ERROR=errors.New("exception.auth.keystone.autherror")
